# Data Preparation and Cleaning

Import essential libraries

In [21]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from IPython.display import display
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

## Dataset 1 - League of Legends - 2024 Competitive Game Dataset

Checking how many columns are in the dataset.

In [22]:
raw_match_data = pd.read_csv('datasets/2024_LoL_esports_match_data_from_OraclesElixir_gamedata.csv', sep=',')
display(raw_match_data)

,gameid,datacompleteness,league,year,split,playoffs,date,game,patch,gamelength,...,t2p5_deathsat10,t2p5_goldat15,t2p5_xpat15,t2p5_csat15,t2p5_golddiffat15,t2p5_xpdiffat15,t2p5_csdiffat15,t2p5_killsat15,t2p5_assistsat15,t2p5_deathsat15
0,10660-10660_game_3,partial,DCup,2023,NaN,0,1/1/2024 6:54,3,13.24,1324,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,LOLTMNT05_13659,complete,LPLOL,2024,Spring,0,26/1/2024 19:10,1,14.01,1364,...,2.0,3666.0,3845.0,22.0,-1115.0,494.0,10.0,0.0,1.0,3.0
2,LOLTMNT04_24264,complete,LEC,2024,Winter,1,3/2/2024 18:47,2,14.02,1350,...,0.0,3692.0,3499.0,14.0,-1090.0,-1025.0,-22.0,1.0,0.0,2.0
3,LOLTMNT01_52094,complete,ESLOL,2024,Spring,0,8/2/2024 19:11,1,14.02,1357,...,0.0,3915.0,3670.0,17.0,-398.0,-290.0,-1.0,1.0,2.0,1.0
4,LOLTMNT02_29074,complete,LCK,2024,Spring,0,24/1/2024 9:00,2,14.01,1283,...,0.0,3738.0,3962.0,22.0,-711.0,-431.0,-29.0,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1018,LOLTMNT05_13780,complete,LEC,2024,Winter,0,28/1/2024 16:13,1,14.01,2963,...,2.0,4024.0,3791.0,29.0,-129.0,-333.0,6.0,1.0,3.0,3.0
1019,10698-10698_game_1,partial,LPL,2024,Spring,0,4/2/2024 11:19,1,14.01,3180,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1020,LOLTMNT02_33054,complete,LJL,2024,Spring,0,27/1/2024 11:24,2,14.01,2950,...,0.0,4164.0,4138.0,84.0,401.0,185.0,65.0,0.0,0.0,1.0
1021,10752-10752_game_1,partial,LDL,2024,Placements,0,3/2/2024 8:19,1,14.01,2923,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1022,LOLTMNT02_23326,complete,PCS,2024,Spring,0,19/1/2024 13:28,2,14.01,3226,...,1.0,3722.0,3640.0,31.0,-597.0,-245.0,3.0,0.0,1.0,2.0

Reducing the number of columns to a few desired columns, which will be further processed in EDA.

In [ ]:
desired_columns = raw_match_data[['t1_result', 't2_result', 't1p1_champion', 't1p2_champion', 't1p3_champion', 't1p4_champion', 't1p5_champion', 't2p1_champion', 't2p2_champion', 't2p3_champion', 't2p4_champion', 't2p5_champion']]

clean_raw_data = pd.DataFrame(raw_match_data[['t1_result', 't2_result', 't1p1_champion', 't1p2_champion', 't1p3_champion', 't1p4_champion', 't1p5_champion', 't2p1_champion', 't2p2_champion', 't2p3_champion', 't2p4_champion', 't2p5_champion']])
# clean_data.head()

In [23]:

# # 2024_LoL_esports_match_data_from_OraclesElixir_gamedata_v4.csv
# all_data = pd.read_csv('2024_LoL_esports_match_data_from_OraclesElixir_gamedata_v4.csv', sep=',')
# all_data.head()

# clean_data = pd.DataFrame(all_data[['t1_result', 't2_result', 't1p1_champion', 't1p2_champion', 't1p3_champion', 't1p4_champion', 't1p5_champion', 't2p1_champion', 't2p2_champion', 't2p3_champion', 't2p4_champion', 't2p5_champion']])
# clean_data.head()

# # Response
# team1 = pd.DataFrame(clean_data[['t1_result', 't1p1_champion', 't1p2_champion', 't1p3_champion', 't1p4_champion', 't1p5_champion']])
# # Predictor
# team2 = pd.DataFrame(clean_data[['t2_result', 't2p1_champion', 't2p2_champion', 't2p3_champion', 't2p4_champion', 't2p5_champion']])

# team1.columns = ['result', 'p1', 'p2', 'p3', 'p4', 'p5']
# team2.columns = ['result', 'p1', 'p2', 'p3', 'p4', 'p5']

# all_team = pd.concat([team1, team2], ignore_index=True)
# display(all_team)

# # ------------------------------------------------------------------------------

# # LOL-Champions.csv
# champion_data = pd.read_csv('LoL-Champions.csv')
# clean_champion_data = pd.DataFrame(champion_data[['Name', 'Class']])

# # ------------------------------------------------------------------------------

# # Merging both data sets
# merged_data = pd.merge(all_team, clean_champion_data, left_on='p1', right_on='Name', how='left')
# merged_data.rename(columns={'Class': 'p1_class'}, inplace=True)
# merged_data.drop('Name', axis=1, inplace=True)

# merged_data = pd.merge(merged_data, clean_champion_data, left_on='p2', right_on='Name', how='left')
# merged_data.rename(columns={'Class': 'p2_class'}, inplace=True)
# merged_data.drop('Name', axis=1, inplace=True)

# merged_data = pd.merge(merged_data, clean_champion_data, left_on='p3', right_on='Name', how='left')
# merged_data.rename(columns={'Class': 'p3_class'}, inplace=True)
# merged_data.drop('Name', axis=1, inplace=True)

# merged_data = pd.merge(merged_data, clean_champion_data, left_on='p4', right_on='Name', how='left')
# merged_data.rename(columns={'Class': 'p4_class'}, inplace=True)
# merged_data.drop('Name', axis=1, inplace=True)

# merged_data = pd.merge(merged_data, clean_champion_data, left_on='p5', right_on='Name', how='left')
# merged_data.rename(columns={'Class': 'p5_class'}, inplace=True)
# merged_data.drop('Name', axis=1, inplace=True)

# columns_order = ['result', 'p1', 'p1_class', 'p2', 'p2_class', 'p3', 'p3_class', 'p4', 'p4_class', 'p5', 'p5_class']
# final_clean_team_data = merged_data[columns_order]

# display(merged_data)

# # ------------------------------------------------------------------------------

# # Prediction

# # y = pd.DataFrame(final_clean_team_data[['p1_class', 'p2_class', 'p3_class', 'p4_class', 'p5_class']])
# # X = pd.DataFrame(final_clean_team_data[['result', 'p1_class', 'p2_class', 'p3_class', 'p4_class', 'p5_class']])

# X = pd.DataFrame(final_clean_team_data[['p1_class', 'p2_class', 'p3_class', 'p4_class', 'p5_class']])
# y = pd.DataFrame(final_clean_team_data[['result']])

# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)

## Dataset 2 - Champions Dataset

In [24]:
cleaned_df.to_csv("cleaned_dataset.csv", index=False)

NameError: name 'cleaned_df' is not defined